name: cache workflow
on: 
    workflow_dispatch:

jobs:
    npm_cache:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout codes
              uses: actions/checkout@v4
            - name: install npm packages
              run: npm install
            - name: use axios
              uses: actions/github-script@v7
              with :
                script: |
                 const axios = require('axios');
                 res = await axios.get('https://icanhazdadjoke.com/', {headers:{Accept:'text/plain'}})
                 console.log(res.data)