name: Docker Workflow
on: [workflow_dispatch]
jobs:
    docker-job1:
        runs-on: ubuntu-latest
        container:
            image: node:21-alpine3.18
        env:
            test_Word : "testword"
        steps:
            - name: Print Node version
              run: |
               node -v
               ls -la
            - name: docker step
              id: docker-step
              uses: docker://node:20-alpine3.18
              with:
                entrypoint: /usr/local/bin/node
                args:  -p 2+3
            - name: docker step2
              id: docker-step2
              uses: docker://node:19-alpine3.18
              with:
                entrypoint: /usr/local/bin/node
                args:  -v
            - name: Log env
              run: echo $test_Word
            - uses: actions/checkout@v4
            - name: run custom script
              uses: docker://node:18-alpine3.18
              with:
                entrypoint: ./scripts/node_script.sh
                args:  "some string"
            - name: use my personal docker image
              uses: docker://muhammadolammi/hellodocker
              
            # - name: send slack message
            #   uses: docker://technosophos/slack-notify
            #   env:
            #     SLACK_WEBHOOK: https://hooks.slack.com/services/Txxxxxx/Bxxxxxx/xxxxxxxx
            #     SLACK_TITLE:  From Github Actions
            #     SLACK_MESSAGE: "Actor: ${{github.actor}} Event: ${{github.event_name}}"
            #     SLACK_COLOR: "#723fc4"
               
