name: Docker Workflow
on: [workflow_dispatch]
jobs:
    docker-job1:
        runs-on: ubuntu-latest
        container:
            image: node:21-alpine3.18
        steps:
            - name: Print Node version
              run: |
               node -v
               type node
               ls -a
