name: Manually Triggered

on:
  workflow_dispatch:
    inputs:
      inputString:
          description: "string input"
          type: string
          required: true
          default: "Default Value"
      inputNumber:
        description: "number input"
        type: number
        required: true
        default: 4
      optionInput:
        description: "options input "
        type: choice
        default: "Option 2"
        options:
          - Option 1
          - Option 2
          - Option 3

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - name : Echo infos
              run: |
               echo "hello world"
               echo ${{ inputs.inputString}}