name: Manually Triggered

on:
  workflow_dispatch:
    inputs:
      stringInput:
          description: "string input"
          type: string
          required: true
          default: "Default Value"
      numberInput:
        description: "number input"
        type: number
        required: true
        default: 4
      optionInput:
        description: "options input "
        type: choice
        default: "Option 2"
        options:
          - Option 1
          - Option 2
          - Option 3
      boolInput:
        description: "Boolean input"
        type: boolean
        required: false
      environmentInput:
        description: "environment input"
        type: environment
        required: true
   

      

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - name : Echo infos
              run: |
               echo "hello world"
               echo ${{ inputs.stringInput}}
               echo ${{ inputs.numberInput}}
               echo ${{ inputs.boolInput}}
               echo ${{ inputs.optionInput}}
               echo ${{ inputs.environmentInput}}