name: use reusable workflow
on: 
    workflow_dispatch:


jobs:
    call_reusable_workflow:

        uses: ./.github/workflows/reusableworkflow.yml
        with:
            name: "Muhammad"
        name: call reusable workflow
    use_reusable_workflow:
        runs-on: ubuntu-latest
        steps:
        - name: echo details from reusable workflow
          run: |
           echo date : ${{needs.call_reusable_workflow.outputs.date}}
           echo name : ${{needs.call_reusable_workflow.outputs.formatedName}}
           echo os : ${{needs.call_reusable_workflow.outputs.os}}
