name: use reusable workflow
on: 
    workflow_dispatch:
        inputs:
            name:
                type: string
                required: true
                default: "muhammad"


jobs:
    call_reusable_workflow:
        uses: ./.github/workflows/reusableworkflow.yml
        with:
            name: ${{inputs.name}}
        secrets: inherit
    use_reusable_workflow:
        runs-on: ubuntu-latest
        steps:
        - name: echo details from reusable workflow
          run: |
           echo date : ${{needs}}
        #    echo name : ${{needs.call_reusable_workflow.outputs.formatedName}}
        #    echo os : ${{needs.call_reusable_workflow.outputs.os}}
